# Generated by Django 3.2.11 on 2022-04-23 12:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('vehicles', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalvehicleworkday',
            name='history_user',
        ),
        migrations.RemoveField(
            model_name='historicalvehicleworkday',
            name='vehicle',
        ),
        migrations.RemoveField(
            model_name='historicalvehicleworkday',
            name='worker',
        ),
        migrations.AlterField(
            model_name='expensesvehicleworkday',
            name='vehicle_workday',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='expenses', related_query_name='expenses', to='vehicles.vehicleworkday'),
        ),
        migrations.AlterField(
            model_name='vehicleworkday',
            name='vehicle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='workday', related_query_name='workday', to='vehicles.vehicle'),
        ),
        migrations.AlterField(
            model_name='vehicleworkday',
            name='worker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='workday', related_query_name='workday', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='vehicleworkdayfiles',
            name='vehicle_workday',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='workday_file', related_query_name='workday_file', to='vehicles.vehicleworkday'),
        ),
        migrations.AlterField(
            model_name='vehicleworkdayfiles',
            name='vehicle_workday_expenses',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='workday_file', related_query_name='workday_file', to='vehicles.expensesvehicleworkday'),
        ),
        migrations.DeleteModel(
            name='HistoricalExpensesVehicleWorkday',
        ),
        migrations.DeleteModel(
            name='HistoricalVehicleWorkDay',
        ),
    ]
