# Generated by Django 3.2.11 on 2022-04-23 12:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('vehicles', '0002_auto_20220423_0920'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expensesvehicleworkday',
            name='vehicle_workday',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_query_name='expenses', to='vehicles.vehicleworkday'),
        ),
        migrations.AlterField(
            model_name='vehicleworkday',
            name='vehicle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_query_name='workday', to='vehicles.vehicle'),
        ),
        migrations.AlterField(
            model_name='vehicleworkday',
            name='worker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_query_name='workday', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='HistoricalVehicleWorkDay',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('created', models.DateTimeField(blank=True, editable=False, help_text='Date time on which the object was created.', null=True, verbose_name='created at')),
                ('modified', models.DateTimeField(blank=True, editable=False, help_text='Date time on which the object was last modified.', verbose_name='modified at')),
                ('km_init', models.IntegerField()),
                ('km_finish', models.IntegerField()),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('vehicle', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='workday', to='vehicles.vehicle')),
                ('worker', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='workday', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical vehicle work day',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalExpensesVehicleWorkday',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('created', models.DateTimeField(blank=True, editable=False, help_text='Date time on which the object was created.', null=True, verbose_name='created at')),
                ('modified', models.DateTimeField(blank=True, editable=False, help_text='Date time on which the object was last modified.', verbose_name='modified at')),
                ('description', models.TextField()),
                ('value', models.IntegerField()),
                ('type', models.CharField(choices=[('FINE', 'fine/multa'), ('SERVICE', 'service/servicio/mantenimiento'), ('TICKET', 'parking/estacionamiento'), ('OTHER', 'other/otro')], default='OTHER', max_length=7)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('vehicle_workday', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='expenses', to='vehicles.vehicleworkday')),
            ],
            options={
                'verbose_name': 'historical expenses vehicle workday',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
