# Generated by Django 3.2.11 on 2022-04-23 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0004_auto_20220423_0959'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalvehicle',
            name='km',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vehicle',
            name='km',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
