# Generated by Django 3.2.11 on 2022-05-08 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0007_auto_20220426_1040'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalvehicle',
            name='tolerancia_km',
            field=models.IntegerField(default=500),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='tolerancia_km',
            field=models.IntegerField(default=500),
        ),
    ]
