# Generated by Django 3.2.11 on 2022-05-26 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0008_auto_20220508_1539'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expensesvehicleworkday',
            name='type',
            field=models.CharField(choices=[('MULTA', 'fine/multa'), ('SERVICIO', 'service/servicio/mantenimiento'), ('ESTACIONAMIENTO', 'parking/estacionamiento'), ('OTRO', 'other/otro')], default='OTRO', max_length=30),
        ),
        migrations.AlterField(
            model_name='historicalexpensesvehicleworkday',
            name='type',
            field=models.CharField(choices=[('MULTA', 'fine/multa'), ('SERVICIO', 'service/servicio/mantenimiento'), ('ESTACIONAMIENTO', 'parking/estacionamiento'), ('OTRO', 'other/otro')], default='OTRO', max_length=30),
        ),
    ]
