# Generated by Django 3.2.11 on 2022-05-26 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0009_auto_20220526_0850'),
    ]

    operations = [
        migrations.AddField(
            model_name='expensesvehicleworkday',
            name='fecha_del_pago',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='expensesvehicleworkday',
            name='moneda',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='expensesvehicleworkday',
            name='pagado',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='historicalexpensesvehicleworkday',
            name='fecha_del_pago',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalexpensesvehicleworkday',
            name='moneda',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='historicalexpensesvehicleworkday',
            name='pagado',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
