# Generated by Django 3.2.11 on 2022-06-20 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0010_auto_20220526_0853'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='historicalexpensesvehicleworkday',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical expenses vehicle workday', 'verbose_name_plural': 'historical expenses vehicle workdays'},
        ),
        migrations.AlterModelOptions(
            name='historicalvehicle',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical vehicle', 'verbose_name_plural': 'historical vehicles'},
        ),
        migrations.AlterModelOptions(
            name='historicalvehicleworkday',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical vehicle work day', 'verbose_name_plural': 'historical vehicle work days'},
        ),
        migrations.AlterField(
            model_name='historicalexpensesvehicleworkday',
            name='history_date',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name='historicalvehicle',
            name='history_date',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name='historicalvehicleworkday',
            name='history_date',
            field=models.DateTimeField(db_index=True),
        ),
    ]
