# Generated by Django 3.2.11 on 2022-05-31 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_auto_20220531_0810'),
    ]

    operations = [
        migrations.AddField(
            model_name='expedientesimagenes',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='servicios/expedientes'),
        ),
    ]
